"""Add tx hashes

Revision ID: 27f4cfff024b
Revises: 6cb283d56ab7
Create Date: 2026-08-28 15:25:30.691452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f4cfff024b'
down_revision: Union[str, None] = '6cb283d56ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submit_tx_hash', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('fund_tx_hash', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('settlement_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'settlement_tx_hash')
    op.drop_column('tasks', 'fund_tx_hash')
    op.drop_column('submissions', 'submit_tx_hash')
    # ### end Alembic commands ###
