"""Add verification model

Revision ID: 6cb283d56ab7
Revises: e36c282ce237
Create Date: 2026-08-28 15:13:53.532185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb283d56ab7'
down_revision: Union[str, None] = 'e36c282ce237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('verifier_agent_id', sa.String(), nullable=True),
    sa.Column('model_family', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('stake_committed', sa.Float(), nullable=True),
    sa.Column('injection_flag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_submission_id'), 'verifications', ['submission_id'], unique=False)
    op.create_index(op.f('ix_verifications_task_id'), 'verifications', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('verification_passport', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'verification_passport')
    op.drop_index(op.f('ix_verifications_task_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_submission_id'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
