"""Add ReputationEvent model

Revision ID: a295bb79724d
Revises: 27f4cfff024b
Create Date: 2026-08-28 21:18:03.533447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a295bb79724d'
down_revision: Union[str, None] = '27f4cfff024b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_events_agent_id'), 'reputation_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_reputation_events_task_id'), 'reputation_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_events_task_id'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_agent_id'), table_name='reputation_events')
    op.drop_table('reputation_events')
    # ### end Alembic commands ###
