"""add task verification fields

Revision ID: c1bb19c22625
Revises: 3422ee9bdb97
Create Date: 2026-08-28 13:46:19.603689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bb19c22625'
down_revision: Union[str, None] = '3422ee9bdb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('verification_schema', sa.JSON(), nullable=False))
    op.add_column('tasks', sa.Column('verification_rubric', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('hidden_test_cases', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('bidding_deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('submission_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'submission_deadline')
    op.drop_column('tasks', 'bidding_deadline')
    op.drop_column('tasks', 'hidden_test_cases')
    op.drop_column('tasks', 'verification_rubric')
    op.drop_column('tasks', 'verification_schema')
    # ### end Alembic commands ###
