"""Add submission model

Revision ID: e36c282ce237
Revises: ecbabe37cd91
Create Date: 2026-08-28 14:34:30.232035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36c282ce237'
down_revision: Union[str, None] = 'ecbabe37cd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('output_content', sa.String(), nullable=False),
    sa.Column('output_hash', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_agent_id'), 'submissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_agent_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
