"""Add bid model

Revision ID: ecbabe37cd91
Revises: c1bb19c22625
Create Date: 2026-08-28 14:03:45.281055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbabe37cd91'
down_revision: Union[str, None] = 'c1bb19c22625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('stake_committed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_agent_id'), 'bids', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bids_task_id'), 'bids', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bids_task_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_agent_id'), table_name='bids')
    op.drop_table('bids')
    # ### end Alembic commands ###
